name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  MATRIX-ID:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: test
      shell: bash
      run: echo ${{ inputs.MATRIX-ID }}|jq .name
