---
name: 'Ansible'

on:
  workflow_call:
    inputs:
      CD_FILE:
        type: string
        required: true
  
jobs:
  ansible_job:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set Ansible Variables
        run: |
          for s in $(yq e . -o=j cd.yml | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]"); do
            echo $s >> $GITHUB_ENV
          done

      # yamlを読み込んでenv設定を行う
      - name: convert env
        run: |
          for s in $(yq e ".${GITHUB_REF#refs/heads/}" -o=j environments.yml | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]"); do
            echo $s >> $GITHUB_ENV
          done

      - name: print env
        run: printenv
