---
name: 'calltest2'

on:
  workflow_call:
    inputs:
      ENV_FILE:
        type: string
        required: true

jobs:
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
          cp ./${{ inputs.ENV_FILE }} ./.env
          cat ./.env
