name: Use reusable flow

on:
  push

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      something: ${{ steps.set-matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - name: make values
        id: set-matrix
        run: |
          echo '["{\"name\": \"a\"}","{\"name\": \"b\"}"]' | jq -c
          list='['
          for s in $(jq .[] matrix.json| jq -c|jq @json); do
            list=${list}"${s}",
          done
          # 変数listの最後の文字','を']'に置換
          list=$(echo $list | sed -e 's/\,$/\]/g')
          echo $list
          echo "value=${list}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        id: ${{fromJson(needs.set-matrix.outputs.something)}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/matrix-test/
        with:
          MATRIX-ID: ${{ matrix.id }}
