name: Use reusable flow

on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create Value
        run: |
          test=`echo "[{\"name\": \"a\"},{\"name\": \"b\"}]"|jq '@json'`
          echo matrix=$test >> $GITHUB_ENV
      - name: printenv
        run: printenv
