name: Use reusable flow

on:
  push

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: read json
        run: |
          # 変数STRにlist=という文字列を代入
          STR='list=['
          
          # test.jsonをjqコマンドでパースして、1行ずつ処理
          for s in $(jq -c .[] matrix.json); do
            # 変数sをjsonエスケープする
            s=$(echo $s | jq -sRr @json)
            # '\n\を削除
            s=$(echo $s | sed -e 's/\\n//g')
            # STRにsを追加
            STR="${STR}${s}"
            # for文の最後以外は変数STRに','を追加する
            if [ $s != $(jq -c .[] test.json | tail -n 1) ]; then
              STR="${STR},"
            else
              echo $s
            fi
          done
          # 最後の,を削除
          STR=$(echo $STR | sed -e 's/,$//g')
          #STRに']'を追加
          STR="${STR}]"
          echo $STR
