name: Use reusable flow

on:
  push:

env:
  ANSIBLE_VERSION: '2.10.7'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      something: ${{ steps.set-matrix.outputs.value }}
      ready: ${{ steps.set-matrix.outputs.ready }}
    steps:
      - uses: actions/checkout@v4
      - name: make values
        id: set-matrix
        run: |
          # sample
          echo '["{\"name\": \"a\"}","{\"name\": \"b\"}"]' | jq -c

          # initial var
          list='['
          ready='false'
          # jsonの配列単位でイテレーション
          for s in $(jq .[] matrix.json| jq -c|jq @json); do
            # "", で囲って配列として連結
            list=${list}"${s}",
            ready='true'
          done
          # 変数listの最後の文字','を']'に置換
          list=$(echo $list | sed -e 's/\,$//g')
          list=$list]
          # debug
          echo $list
          # set output
          echo "value=${list}" >> $GITHUB_OUTPUT
          echo "ready=${ready}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: set-matrix
    if: needs.set-matrix.outputs.something != '[]'
    steps:
      - name: 'debug'
        run: "echo  ${{ needs.set-matrix.outputs.something }}"
      - name: 'debug2'
        run: "echo  ${{ needs.set-matrix.outputs.ready }}"
  example_matrix:
    runs-on: ubuntu-20.04
    needs: set-matrix
    if: needs.set-matrix.outputs.ready == 'true'
    strategy:
      matrix:
        id: ${{fromJson(needs.set-matrix.outputs.something)}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/matrix-test/
        with:
          MATRIX-ID: ${{ matrix.id }}
