on: [push]

env:
  env_1: envtest

jobs:
  envtest_job:
    runs-on:  ubuntu-20.04
    steps:

      - name: print env
        run: echo ${{env.env_1}}

      - name: checkout
        uses: actions/checkout@main

      - name: convert env
        run: |
          cat environments.json | \
          jq -r --arg key "${GITHUB_REF#refs/heads/}" to_entries | map("\(.key)=\(.value)") | .[]'

