name: Use reusable flow

on:
  push

jobs:
  constants:
    name: Constants
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          for json in $(jq -c .params[] matrix.json); do
            echo "matrix=${json}"
          done
