on: [push]

jobs:
  call_action1:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: ls -l
      
      - name: test2
        run: 'echo hogehoge > hoge.txt'

      - name: other workflow
        uses: ./.github/workflows/call.yml
