name: Use reusable flow

on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set output value
        id: step1
        run: |
          echo "::set-output name=param1::1,2,3"
    outputs:
      param1: ${{ steps.step1.outputs.param1 }}

  example_matrix:
    runs-on: ubuntu-20.04
    needs: job1
    strategy:
      matrix:
        id: "${{ needs.job1.outputs.param1 }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/matrix-test/
        with:
          MATRIX-ID: ${{ matrix.id }}
