on: [push]

jobs:
  envtest_job:
    runs-on:  ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: convert env
        run: |
          cat environments.json | \
          jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' | \
          while read line; do echo "$line" >> $GITHUB_ENV; done

      - name: print env
        run: printenv
