name: main
on: [push]

env:
  HELLO_WORLD: HelloWorld
jobs:
  myjob:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: print json file
        run: echo "${{env.HELLO_WORLD}}"
