on: [push]

jobs:
  example_matrix:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        id: [10, 12, 14]
    steps:
      - uses: ./.github/actions/matrix-test.yml
        with:
          matrix-id: ${{ matrix.id }}
