name: Use reusable flow

on:
  push

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      something: ${{ steps.set-matrix.outputs.value }}
    steps:
      - name: make values
        id: set-matrix
        run: |
          echo '["{\"name\": \"a\"}","{\"name\": \"b\"}"]' | jq -c
          list=$(echo '["{\"name\": \"a\"}","{\"name\": \"b\"}"]' | jq -c)
          echo "value=${list}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        id: ${{fromJson(needs.set-matrix.outputs.something)}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/matrix-test/
        with:
          MATRIX-ID: ${{ matrix.id }}
