name: Use reusable flow

on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create Value
        run: |
          echo '["hoge","fuga"]' | jq -c
          list=$(echo '["hoge","fuga"]' | jq -c)
          echo "matrix=${list}" >> $GITHUB_OUTPUT

      - name: printenv
        run: printenv

      - name: Set output value
        id: step1
        run: |
          echo "::set-output name=param1::${{ env.matrix }}"
    outputs:
      param1: ${{ steps.step1.outputs.param1 }}

  example_matrix:
    runs-on: ubuntu-20.04
    needs: job1
    strategy:
      matrix:
        id: ${{fromJson(needs.job1.outputs.param1)}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/matrix-test/
        with:
          MATRIX-ID: ${{ matrix.id }}
