name: Reusable workflow B

on:
  workflow_call:
    inputs:
      param1:
        description: 'Param1'
        required: true
        type: string
      param2:
        description: 'Param2'
        required: false
        type: string
        default: 'default-param2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printenv
        run: printenv
      - name: Echo
        run: echo "called from reusable flow with param ${{ inputs.param1 }} & ${{ inputs.param2 }}!"
