name: Reusable workflow A

on:
  workflow_call:
    inputs:
      param1:
        description: 'Param1'
        required: true
        type: string

jobs:
  setup_params:
    runs-on: ubuntu-20.04
    steps:
      - name: setup
        run: |
          echo 'param1=HOGE' >> $GITHUB_ENV
          echo 'param2=MOGE' >> $GITHUB_ENV
      - name: printenv
        run: printenv
  call-another-reusable:
    uses: ./.github/workflows/nested-flow.yml
    with:
      param1: '${{ env.param1 }}'
      param2: '${{ env.param2 }}'
