name: Reusable workflow A

on:
  workflow_call:
    inputs:
      param1:
        description: 'Param1'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set output value
        id: step1
        run: echo "::set-output name=my_output::Hello, from Job 1"
    outputs:
      job1_output: ${{ steps.step1.outputs.my_output }}

  call-another-reusable:
    needs: job1
    uses: ./.github/workflows/nested-flow.yml
    with:
      param1:  ${{ needs.job1.outputs.job1_output }}
