name: Reusable workflow A

on:
  workflow_call:
    inputs:
      param1:
        description: 'Param1'
        required: true
        type: string

jobs:
  setup_params:
    runs-on: ubuntu-20.04
    steps:
      - name: setup
        run: |
          echo 'param1=HOGE' >> $GITHUB_ENV
          echo 'param2=MOGE' >> $GITHUB_ENV
      - name: printenv
        run: printenv
        
      - name: printenv2
        run: echo ${{ github.env }}
  
      - id: stepid
        run: echo "::set-output name=value::${{ github.env.param1 }}"
      outputs:
        value: ${{ steps.stepid.outputs.value }}

  call-another-reusable:
    needs: setup_params
    uses: ./.github/workflows/nested-flow.yml
    with:
      param1: '${{ needs.setup_params.param1 }}'
