name: Reusable workflow A

on:
  workflow_call:
    inputs:
      param1:
        description: 'Param1'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set output value
        id: step1
        run: |
          echo "::set-output name=param1::HOGE"
          echo "::set-output name=param2::MOGE"
    outputs:
      param1: ${{ steps.step1.outputs.param1 }}
      param2: ${{ steps.step1.outputs.param2 }}

  call-another-reusable:
    needs: job1
    uses: ./.github/workflows/nested-flow.yml
    with:
      param1:  ${{ needs.job1.outputs.param1 }}
      param2:  ${{ needs.job1.outputs.param2 }}
