name: Run Playbooks

on: [push]

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Read playbooks.yml
        id: read-playbooks
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const fileContents = fs.readFileSync('playbooks.yml', 'utf8');
            const data = yaml.load(fileContents);
            return JSON.stringify(data);

      - name: Run Playbooks
        run: |
          result='${{ steps.read-playbooks.outputs.result }}'
          for item in $(echo "$result" | jq -c '.[]'); do
            echo $item
          done
        env:
          result: ${{ steps.read-playbooks.outputs.result }}
