name: Run Playbooks

on: [push]

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    outputs:
      something: ${{ steps.set-matrix.outputs.value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Read playbooks.yml
        id: read-playbooks
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const fileContents = fs.readFileSync('playbooks.yml', 'utf8');
            const data = yaml.load(fileContents);
            return JSON.stringify(data);

      - name: make values
        id: set-matrix
        run: |
          # sample
          echo '["{\"name\": \"a\"}","{\"name\": \"b\"}"]' | jq -c

          result='${{ steps.read-playbooks.outputs.result }}'
          # initial var
          list='['
          # jsonの配列単位でイテレーション
          for s in $(echo $result|jq -r|jq .[]| jq -c|jq @json); do
            # "", で囲って配列として連結
            list=${list}"${s}",
          done
          # 変数listの最後の文字','を']'に置換
          list=$(echo $list | sed -e 's/\,$//g')
          list=$list]
          # debug
          echo $list
          # set output
          echo "value=${list}"
          echo "value=${list}" >> $GITHUB_OUTPUT
        env:
          result: ${{ steps.read-playbooks.outputs.result }}
          # set output

  example_matrix:
    runs-on: ubuntu-20.04
    needs: run-playbooks
    if: needs.run-playbooks.outputs.something != '[]'
    strategy:
      matrix:
        id: ${{fromJson(needs.run-playbooks.outputs.something)}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/matrix-test/
        with:
          MATRIX-ID: ${{ matrix.id }}
