name: Run Playbooks

on: [push]

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Read playbooks.yml
        id: read-playbooks
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const fileContents = fs.readFileSync('playbooks.yml', 'utf8');
            const data = yaml.load(fileContents);
            return { result: JSON.stringify(data) }

      - name: Run Playbooks
        run: |
          echo '${{ steps.read-playbooks.outputs.result }}' > result.json
          for item in $(cat result.json | jq -c '.[]'); do
            PLAYBOOK=$(echo $item | jq -r '.PLAYBOOK')
            INVENTORY=$(echo $item | jq -r '.INVENTORY')
            echo "Running playbook: $PLAYBOOK with inventory: $INVENTORY"
            # ここにAnsibleコマンドを追加
            # ansible-playbook -i $INVENTORY $PLAYBOOK
          done
