---
  name: Main Action
  on:
    push:
  
  jobs:
    ansible-lint-customver_job:
      uses: ./.github/workflows/a.yml
  
    ansible-job:
      uses: ./.github/workflows/b.yml
      needs: ansible-lint-customver_job
